### ISSUE TITLE
Keep waiting until ... while enough btc received at fund address

### ISSUE THREAD

**Issue by srdwinu** [atomicals/atomicals-js#138]
Enough BTC was sent to fund address but mint-dft does not work. How to make it work?

**Comment by Songhan17** [comment]
> Enough BTC was sent to fund address but mint-dft does not work. How to make it work?

Hey, bro, how did you solve the problem?

**Comment by srdwinu** [comment]
> > Enough BTC was sent to fund address but mint-dft does not work. How to make it work?
> 
> Hey, bro, how did you solve the problem?

No,sir. I thought to mint neutron before, but then changed to proton and it worked. So have no idea what happened 🫠. You can new issue with more detail.

**Comment by Songhan17** [comment]
> > > Enough BTC was sent to fund address but mint-dft does not work. How to make it work?
> > 
> > 
> > Hey, bro, how did you solve the problem?
> 
> No,sir. I thought to mint neutron before, but then changed to proton and it worked. So have no idea what happened 🫠. You can new issue with more detail.

I see. Thank you
