### ISSUE TITLE
a bug for dft bitwork mint

### ISSUE THREAD

**Issue by ipoh123** [atomicals/atomicals-js#143]
please check this https://live.blockcypher.com/btc/tx/0000000094369b09906594d7fa037c45181357031ffbe5bd075dac72d39a3cfd/

he make 100 neutrons with only one hash work

**Comment by pan3da** [comment]
Why close this issue?

**Comment by pan3da** [comment]
@atomicals 
tx is here: https://mempool.space/tx/0000000094369b09906594d7fa037c45181357031ffbe5bd075dac72d39a3cfd
neutron balance: https://bitatom.io/address/bc1q5k2h0qdjwrsc8pzumcvff62rq3fn6t5dy5l9q6?tab=tokens

**Comment by pan3da** [comment]
This PR fixes the issue: https://github.com/atomicals/atomicals-electrumx/pull/38
