### ISSUE TITLE
Missing index one mint by mint-dft

### ISSUE THREAD

**Issue by citymaster** [atomicals/atomicals-js#171]
Hello,

Here's the commit txs: 
aabbcc43eb14d59d12b21f1519314177786000095d99e7bb764ce9c75ec5461b
d4cde85c7a658f77012ea2eb2d55c07accca065b9bdba288cfbf030e59b111a7

I'm minting quark, sent two transcations but got only one mint.

BR

**Comment by pan3da** [comment]
The second tx seems not a valid mint. Valid commit txid is started with `aabbcc`.

**Comment by citymaster** [comment]
> The second tx seems not a valid mint. Valid commit txid is started with `aabbcc`.

Thanks pan3da, seems you're right.

**Comment by yujianFresh** [comment]
hi,i stop the cli, and the mint not receive.
my fund address mint trx: https://mempool.space/tx/aabbcc004fe45ae61451f208457f32050fdd0476c5340b0a1441b4456102063f

how to re broadcast the commit trx ？
