### ISSUE TITLE
[BUG]Get TypeError while executing "yarn cli set-container-data ..."

### ISSUE THREAD

**Issue by maogongyin** [atomicals/atomicals-js#194]
Hi, I'm working on a NFT project involved with DMINT.
I was stuck at 
```
$ yarn cli set-container-data "#container-name" "path/to/container-dmint-metadata.json" --satsbyte=1.
```
The output tells there's an issue with 
```copiedData["args"]["nonce"] = Math.floor(Math.random() * 10000000)``` :
```shell
Stay calm and grab a drink! Miner workers have started mining... 
worker error:  TypeError [Error]: Cannot set properties of undefined (setting 'nonce')
    at /Users/maoma/nodejs/atomicals-js/dist/utils/miner-worker.js:45:37
    at Generator.next (<anonymous>)
    at /Users/maoma/nodejs/atomicals-js/dist/utils/miner-worker.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/maoma/nodejs/atomicals-js/dist/utils/miner-worker.js:4:12)
    at MessagePort.<anonymous> (/Users/maoma/nodejs/atomicals-js/dist/utils/miner-worker.js:36:60)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:639:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

I am on the latest commit:
commit 6db26e236dcb3a4a4b8526e7272f877b8e81d39a (origin/master, origin/HEAD), and I have also confirmed that my container metadata is correct.

**Comment by Brochen** [comment]
try add   --bitworkc="xxx"

**Comment by FlippedToothy** [comment]
you can add --bitworkc = "you set hard level"  to fix it

**Comment by Brochen** [comment]
> you can add --bitworkc = "you set hard level" to fix it
> 
> for example
> 
> $ yarn cli set-container-data "#container-name" "path/to/container-dmint-metadata.json" --satsbyte=1 --bitworkc = "0000"

yes, it worked

**Comment by maogongyin** [comment]
> you can add --bitworkc = "you set hard level" to fix it
> 
> for example
> 
> $ yarn cli set-container-data "#container-name" "path/to/container-dmint-metadata.json" --satsbyte=1 --bitworkc = "0000"

Works like a charm. Thank you!
