### ISSUE TITLE
How to resume interrupted reveal tx or refund for the BTC?

### ISSUE THREAD

**Issue by 121812** [atomicals/atomicals-js#244]
Hello, my commit transaction was successful, but unfortunately, the program was interrupted during the generation of the reveal transaction.
console log:
```
Detected Funding UTXO (00000049c1f72640d94901c80d0db8acdb21b0308b5eb1ed651e550e25ff6487:0) with value 109887 for funding...

Atomicals Bitwork Mining - Requested bitwork proof-of-work mining for the reveal transaction.
bitworkr (input): 6238
bitworkr (decoded): 6238
---------
WARNING: This might take a very long time depending on the speed of the CPU.
Time to mine estimates: 
- prefix length <= 4: about a minute or two. ~65,536 hashes on average.
- prefix length 5: several minutes. ~1,048,576 hashes on average.
- prefix length 6: up to an hour or more. ~16,777,216 hashes on average.
- prefix length >= 7: a few hours or much longer. >268,435,456 hashes on average.

Starting mining now...

a4ffa2b5f4e937f8504f1d359746dc3c213c4a6de04e16023c0df4ec2db44480  nonces:  41715
```

May I inquire about the possibility of recovering the transaction or initiating a refund for the BTC in the P2TR address?

**Comment by atlaslabsapp** [comment]
Do you have the log just before broadcasting the commit transaction?  If you do,  find `time` and `nonce` on it , then try this: https://github.com/atlaslabsapp/atomicals-js/tree/handle_no_reveal

**Comment by 121812** [comment]
"go one finalCopyData" is not found in this log，Is there any possibility of remedy if there is no nonce and time during the log ?
The latest version I use, commit id:d890c1ef7aa4bae709f43d8d8926a746ef5239d3.


```
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
Worker stopped with exit code 1
...
Detected Funding UTXO (00000049c1f72640d94901c80d0db8acdb21b0308b5eb1ed651e550e25ff6487:0) with value 109887 for funding...

Atomicals Bitwork Mining - Requested bitwork proof-of-work mining for the reveal transaction.
bitworkr (input): 6238
bitworkr (decoded): 6238
---------
WARNING: This might take a very long time depending on the speed of the CPU.
Time to mine estimates: 
- prefix length <= 4: about a minute or two. ~65,536 hashes on average.
- prefix length 5: several minutes. ~1,048,576 hashes on average.
- prefix length 6: up to an hour or more. ~16,777,216 hashes on average.
- prefix length >= 7: a few hours or much longer. >268,435,456 hashes on average.

Starting mining now...

a4ffa2b5f4e937f8504f1d359746dc3c213c4a6de04e16023c0df4ec2db44480  nonces:  41715
Socket error Event: 32 Error: 10053.
```

**Comment by MrBWG** [comment]
> Do you have the log just before broadcasting the commit transaction? If you do, find `nonce` and `time` on it , then try this: https://github.com/atlaslabsapp/atomicals-js/tree/handle_no_reveal
> 
> ![image](https://private-user-images.githubusercontent.com/152697231/297799813-3f4c0b7a-384d-4bf7-8c8c-8c3c05abf733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Mzg4MTksIm5iZiI6MTcwNTYzODUxOSwicGF0aCI6Ii8xNTI2OTcyMzEvMjk3Nzk5ODEzLTNmNGMwYjdhLTM4NGQtNGJmNy04YzhjLThjM2MwNWFiZjczMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwNDI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTQyN2M2ZjE0NDEyZjU0ZGZkZGI5ZDBjZTEwYjAyNWQ3YjMyODQzZDc4MTAzYTlkZDI0ODc1YThhYjg2YmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lKSnT3Y5JjR2_SuiwrOL8lI8gSVbFNkcVRmv_S9Bxn0)



> Do you have the log just before broadcasting the commit transaction? If you do, find `nonce` and `time` on it , then try this: https://github.com/atlaslabsapp/atomicals-js/tree/handle_no_reveal
> 
> ![image](https://private-user-images.githubusercontent.com/152697231/297799813-3f4c0b7a-384d-4bf7-8c8c-8c3c05abf733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2Mzg4MTksIm5iZiI6MTcwNTYzODUxOSwicGF0aCI6Ii8xNTI2OTcyMzEvMjk3Nzk5ODEzLTNmNGMwYjdhLTM4NGQtNGJmNy04YzhjLThjM2MwNWFiZjczMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwNDI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTQyN2M2ZjE0NDEyZjU0ZGZkZGI5ZDBjZTEwYjAyNWQ3YjMyODQzZDc4MTAzYTlkZDI0ODc1YThhYjg2YmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lKSnT3Y5JjR2_SuiwrOL8lI8gSVbFNkcVRmv_S9Bxn0)

I used your code to reconstruct the reveal transaction data, but when broadcasting, I get the following signature error, how do I fix it?
non-mandatory-script-verify-flag (Invalid Schnorr signature)

**Comment by atlaslabsapp** [comment]
I've also encountered a situation where logs fail to display in a multi-threaded environment before; I'm not sure if that is the case this time. However, after studying the latest version of the code, I found that the `nonce` has been changed to a fixed value of `0`, so it is only necessary to enumerate the `time`. I've modified my program, and you can enumerate the time according to the following configuration.
``` 
commitTxid=00000049c1f72640d94901c80d0db8acdb21b0308b5eb1ed651e550e25ff6487
time=
nonce=0
```
In fact your `time` value is `1705585297`, you can also fill it in to save your time.

**Comment by joeqiaoyao** [comment]
> I've also encountered a situation where logs fail to display in a multi-threaded environment before; I'm not sure if that is the case this time. However, after studying the latest version of the code, I found that the `nonce` has been changed to a fixed value of `0`, so it is only necessary to enumerate the `time`. I've modified my program, and you can enumerate the time according to the following configuration.
> 
> ```
> commitTxid=00000049c1f72640d94901c80d0db8acdb21b0308b5eb1ed651e550e25ff6487
> time=
> nonce=0
> ```
> 
> In fact your `time` value is `1705585297`, you can also fill it in to save your time.

How get timestamp obtained through commitTxid?

`00000032fe64ad1d112b1749ee6bc0ef2f4bebba59c2ccb6d75e4862b6838e93`
 my commit transaction also lost time and nonce.

Thank you!

**Comment by atlaslabsapp** [comment]
@joeqiaoyao  You can't get `time` direct from commitTxid, but you can get tx broadcast time `1705661086` from 
 https://www.blockchain.com/explorer/transactions/btc/00000032fe64ad1d112b1749ee6bc0ef2f4bebba59c2ccb6d75e4862b6838e93 

If the time between your computer and blockchain.com are synced, your `time` should equal of less that tx broadcast time `1705661086`.  So you can set `time=1705661086` in `.env`, the program will try 1705661086, 1705661085, 1705661084... until it find the right value. 

I visit your mint history and find your`nonce` isn't the constant `0`. If you don't have the right `nonce`, there will be 10000000 `nonce` to enumerate for ***every*** `time`. It will make a few hours to several days. You should decide if it is worth it. 

There are more about execute time in [Readme](https://github.com/atlaslabsapp/atomicals-js/blob/handle_no_reveal/README.md#usage) as follow.


> Based on the status of different parameter inputs, the expected completion time varies:
> 
> - If both `time` and `nonce` are filled in correctly: immediate (or pending reveal bitwork completion)
> - If only `time` is filled in correctly: a few hours to several days
> - If only `nonce` is filled in correctly: a few seconds to several minutes
> - If neither `time` nor `nonce` is filled in: virtually impossible. Find 'time' in your commit tx log or https://www.blockchain.com/explorer/

**Comment by joeqiaoyao** [comment]
@atlaslabsapp 

`Start with config time: 1705661086
Concurrency set to: 55
Initializing worker: 0
Initializing worker: 1
Initializing worker: 2
Initializing worker: 3
Initializing worker: 4
Initializing worker: 5
Initializing worker: 6
Initializing worker: 7
Initializing worker: 8
Initializing worker: 9
Initializing worker: 10
Initializing worker: 11
Initializing worker: 12
Initializing worker: 13
Initializing worker: 14
Initializing worker: 15
Initializing worker: 16
Initializing worker: 17
Initializing worker: 18
Initializing worker: 19
Initializing worker: 20
Initializing worker: 21
Initializing worker: 22
Initializing worker: 23
Initializing worker: 24
Initializing worker: 25
Initializing worker: 26
Initializing worker: 27
Initializing worker: 28
Initializing worker: 29
Initializing worker: 30
Initializing worker: 31
Initializing worker: 32
Initializing worker: 33
Initializing worker: 34
Initializing worker: 35
Initializing worker: 36
Initializing worker: 37
Initializing worker: 38
Initializing worker: 39
Initializing worker: 40
Initializing worker: 41
Initializing worker: 42
Initializing worker: 43
Initializing worker: 44
Initializing worker: 45
Initializing worker: 46
Initializing worker: 47
Initializing worker: 48
Initializing worker: 49
Initializing worker: 50
Initializing worker: 51
Initializing worker: 52
Initializing worker: 53
Initializing worker: 54
Waiting for workers to complete...
Nonces:  0 , time:  1705694809
Nonces:  2000000 , time:  1705694810
Nonces:  4000000 , time:  1705694810
Nonces:  8000000 , time:  1705694810
Nonces:  6000000 , time:  1705694810
Nonces:  910000 , time:  1705694814
Nonces:  6910000 , time:  1705694814
Nonces:  2910000 , time:  1705694814
Nonces:  4910000 , time:  1705694814
Nonces:  8910000 , time:  1705694814
Nonces:  1820000 , time:  1705694818
Nonces:  3820000 , time:  1705694818
Nonces:  5820000 , time:  1705694818
Nonces:  7820000 , time:  1705694818
Nonces:  9820000 , time:  1705694818
Nonces:  730000 , time:  1705694822
Nonces:  2730000 , time:  1705694822
Nonces:  8730000 , time:  1705694822
Nonces:  4730000 , time:  1705694822
Nonces:  6730000 , time:  1705694822
Nonces:  1640000 , time:  1705694825
Nonces:  7640000 , time:  1705694826
Nonces:  9640000 , time:  1705694826
Nonces:  3640000 , time:  1705694826
Nonces:  5640000 , time:  1705694826
Nonces:  550000 , time:  1705694829
Nonces:  8550000 , time:  1705694829
Nonces:  2550000 , time:  1705694829
Nonces:  6550000 , time:  1705694829
Nonces:  4550000 , time:  1705694829
Nonces:  3460000 , time:  1705694833
Nonces:  5460000 , time:  1705694833
Nonces:  1460000 , time:  1705694833
Nonces:  9460000 , time:  1705694833
Nonces:  7460000 , time:  1705694833
Nonces:  370000 , time:  1705694836
Nonces:  4370000 , time:  1705694836
Nonces:  8370000 , time:  1705694836
Nonces:  2370000 , time:  1705694836
Nonces:  6370000 , time:  1705694837
Nonces:  7280000 , time:  1705694840
Nonces:  3280000 , time:  1705694840
Nonces:  1280000 , time:  1705694840
Nonces:  9280000 , time:  1705694840
Nonces:  5280000 , time:  1705694840
Nonces:  4190000 , time:  1705694843
Nonces:  190000 , time:  1705694843
Nonces:  6190000 , time:  1705694843
Nonces:  2190000 , time:  1705694844
Nonces:  8190000 , time:  1705694844
`
I try it. But time keeps increasing, not decreasing, is that correct?
Thanks!

**Comment by atlaslabsapp** [comment]
> "go one finalCopyData" is not found in this log，Is there any possibility of remedy if there is no nonce and time during the log ? The latest version I use, commit id:d890c1ef7aa4bae709f43d8d8926a746ef5239d3.

There is a PR #229 to solve the log problem.

**Comment by 121812** [comment]
> I've also encountered a situation where logs fail to display in a multi-threaded environment before; I'm not sure if that is the case this time. However, after studying the latest version of the code, I found that the `nonce` has been changed to a fixed value of `0`, so it is only necessary to enumerate the `time`. I've modified my program, and you can enumerate the time according to the following configuration.
> 
> ```
> commitTxid=00000049c1f72640d94901c80d0db8acdb21b0308b5eb1ed651e550e25ff6487
> time=
> nonce=0
> ```
> 
> In fact your `time` value is `1705585297`, you can also fill it in to save your time.

Thank you so much, through the above method, the reveal tx was successfully sent.
Report a small bug: 
I execute yarn cli mint-dft sophon --satsbyte 38, The gas cost of reveal tx is not equal to 38 but 32.9.
Tx: 6238f5fd50d1061bfa1a55099e2df31646e77eb6f03c54b06a4ba52bbf27d3d0

**Comment by atlaslabsapp** [comment]
> > I've also encountered a situation where logs fail to display in a multi-threaded environment before; I'm not sure if that is the case this time. However, after studying the latest version of the code, I found that the `nonce` has been changed to a fixed value of `0`, so it is only necessary to enumerate the `time`. I've modified my program, and you can enumerate the time according to the following configuration.
> > ```
> > commitTxid=00000049c1f72640d94901c80d0db8acdb21b0308b5eb1ed651e550e25ff6487
> > time=
> > nonce=0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In fact your `time` value is `1705585297`, you can also fill it in to save your time.
> 
> Thank you so much, through the above method, the reveal tx was successfully sent. Report a small bug: I execute yarn cli mint-dft sophon --satsbyte 38, The gas cost of reveal tx is not equal to 38 but 32.9. Tx: 6238f5fd50d1061bfa1a55099e2df31646e77eb6f03c54b06a4ba52bbf27d3d0

 Thank you for your feedback. I cherry-picked https://github.com/atomicals/atomicals-js/pull/243/commits/46f0499d40218e54ad5efe232e7d2500c7ba9f84 to fix this problem.

**Comment by SunSeekerX** [comment]
> > > I've also encountered a situation where logs fail to display in a multi-threaded environment before; I'm not sure if that is the case this time. However, after studying the latest version of the code, I found that the  has been changed to a fixed value of , so it is only necessary to enumerate the . I've modified my program, and you can enumerate the time according to the following configuration.`nonce``0``time`
> > > ```
> > > commitTxid=00000049c1f72640d94901c80d0db8acdb21b0308b5eb1ed651e550e25ff6487
> > > time=
> > > nonce=0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In fact your  value is , you can also fill it in to save your time.`time``1705585297`
> > 
> > 
> > Thank you so much, through the above method, the reveal tx was successfully sent. Report a small bug: I execute yarn cli mint-dft sophon --satsbyte 38, The gas cost of reveal tx is not equal to 38 but 32.9. Tx: 6238f5fd50d1061bfa1a55099e2df31646e77eb6f03c54b06a4ba52bbf27d3d0
> 
> Thank you for your feedback. I cherry-picked [46f0499](https://github.com/atomicals/atomicals-js/commit/46f0499d40218e54ad5efe232e7d2500c7ba9f84) to fix this problem.

夸克和 fanshood 有可能找回吗，只有 commitr 的信息

**Comment by atlaslabsapp** [comment]
> > > > I've also encountered a situation where logs fail to display in a multi-threaded environment before; I'm not sure if that is the case this time. However, after studying the latest version of the code, I found that the  has been changed to a fixed value of , so it is only necessary to enumerate the . I've modified my program, and you can enumerate the time according to the following configuration.`` nonce``0``time ``
> > > > ```
> > > > commitTxid=00000049c1f72640d94901c80d0db8acdb21b0308b5eb1ed651e550e25ff6487
> > > > time=
> > > > nonce=0
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > In fact your  value is , you can also fill it in to save your time.`` time``1705585297 ``
> > > 
> > > 
> > > Thank you so much, through the above method, the reveal tx was successfully sent. Report a small bug: I execute yarn cli mint-dft sophon --satsbyte 38, The gas cost of reveal tx is not equal to 38 but 32.9. Tx: 6238f5fd50d1061bfa1a55099e2df31646e77eb6f03c54b06a4ba52bbf27d3d0
> > 
> > 
> > Thank you for your feedback. I cherry-picked [46f0499](https://github.com/atomicals/atomicals-js/commit/46f0499d40218e54ad5efe232e7d2500c7ba9f84) to fix this problem.
> 
> 夸克和 fanshood 有可能找回吗，只有 commitr 的信息

对于已经结束 mint 的 token，最好的结果是从临时地址里将 BTC 转出来，不能找回 token。需要设置 `refund=true`

请问你说的 `commitr` 具体指的是什么？

**Comment by OooChrisooO** [comment]
> @joeqiaoyao You can't get `time` direct from commitTxid, but you can get tx broadcast time `1705661086` from https://www.blockchain.com/explorer/transactions/btc/00000032fe64ad1d112b1749ee6bc0ef2f4bebba59c2ccb6d75e4862b6838e93
> 
> If the time between your computer and blockchain.com are synced, your `time` should equal of less that tx broadcast time `1705661086`. So you can set `time=1705661086` in `.env`, the program will try 1705661086, 1705661085, 1705661084... until it find the right value.
> 
> I visit your mint history and find your`nonce` isn't the constant `0`. If you don't have the right `nonce`, there will be 10000000 `nonce` to enumerate for _**every**_ `time`. It will make a few hours to several days. You should decide if it is worth it.
> 
> There are more about execute time in [Readme](https://github.com/atlaslabsapp/atomicals-js/blob/handle_no_reveal/README.md#usage) as follow.
> 
> > Based on the status of different parameter inputs, the expected completion time varies:
> > 
> > * If both `time` and `nonce` are filled in correctly: immediate (or pending reveal bitwork completion)
> > * If only `time` is filled in correctly: a few hours to several days
> > * If only `nonce` is filled in correctly: a few seconds to several minutes
> > * If neither `time` nor `nonce` is filled in: virtually impossible. Find 'time' in your commit tx log or https://www.blockchain.com/explorer/

Sorry that I have tried many times researching the timestamp but can't get what you got as a exact timestamp to save time.
Could I have it for below?
commitTxid=000000493118d59f4b1b07da9fdaaccf52b6ccf4770cfd29770f30d5af9c2c9f
