### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by cymqqqq** [atomicals/atomicals-js#27]
When I run npm install:
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/notmasteryet/jpgjs.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

ssh publickey?

**Comment by chrions** [comment]
How did you solve this problem ？
