### ISSUE TITLE
mint-nft Error: Error adding output ;How to use CPFP

### ISSUE THREAD

**Issue by ibiter** [atomicals/atomicals-js#36]
nonces30ffb12d02cddb15e53da5fa218bf34f4bf9b18db052d5123da9366931f5f694ac6777bd2027f594facc86a181643c9d269c348fd5eb31c257fc4342dd87aa6d7d107c446a231716d47da3a460d6d8cf790a52b8a1592154d3b89ddb830344bbe9b8b93bce8f591bd593be7a9653d4089ff7fc988ff3559c213b479a88b43563c685502c6f1b nonces:11380539
a9abd994d33a8ecd84eb30e3f606b4617f5dc8c5f5ffe955aed11f7309134771aa3b3f5e6aa81e4cb13e6d87fec722b92b0ec5e6201e5ab86866ced550515fccef7405f644aae7f1359f645efbb8bcacf49639bf97e0a  nonces: 12112617
Bitwork matches commit txid!  ab86866ced550515fccef7405f644aae7f1359f645efbb8bcacf49639bf97e0a @ time: 1699148342
rawtx 01000000000101899476dccd931c25d210e480ca5035107656a811d31d45322560653df91071810000000000ffffffff0224120000000000002251201f1a94546c0af5b39ded3add068f4147a22ff918de27c82f805c811c7cc6a2b0da6d0100000000002251202c193cfeb25c52feccde93e47bf1ea13c51e97b5996ef7daeec53cd4f818dc1301406e4545e52a650db28b74d9729e2e4f0ce04acf53ba16aa0c908b19024f6ccb09800577a0aea89b815f4122194f326a3661fda56d15c8caf2ae031a9cc5e5c71300000000
Success sent tx:  ab86866ced550515fccef7405f644aae7f1359f645efbb8bcacf49639bf97e0a
...
...
...
...
...
...
Detected Funding UTXO (ab86866ced550515fccef7405f644aae7f1359f645efbb8bcacf49639bf97e0a:0) with value 4644 for funding...
{
  "success": false,
  "message": "Error: Error adding output.",
  "error": {}
}
✨  Done in 11628.49s.

**Comment by b456kh** [comment]
You can try sparrow wallet（https://bitcoin.org/zh_CN/wallets/desktop/windows/sparrow/?step=5&platform=windows）
Import mnemonic words selected format will have your transaction, click on the transaction can use CPFP

**Comment by ibiter** [comment]
This wallet is generated using Atom with 12 seeds. When I import it, choosing the bc1p format generates a different address, while selecting according to m/44 doesn't produce a bc1p address

**Comment by ibiter** [comment]
![？](https://github.com/atomicals/atomicals-js/assets/84977499/4c3b4109-f8cd-44e7-a72a-787cd4beb856)

**Comment by ibiter** [comment]
Yes, that's what I did

**Comment by ibiter** [comment]
I found the --parent and --parentowner functions in mint-nft, and I want to know how they are used

**Comment by b456kh** [comment]
![1](https://github.com/atomicals/atomicals-js/assets/5693221/4c03274e-7312-46c4-8916-cae6249433a1)
![2](https://github.com/atomicals/atomicals-js/assets/5693221/29c05d86-16e3-4f4c-8d67-2b5013f21cbf)

This import will scan your address directly without requiring you to select the m44 or m86 type

**Comment by ibiter** [comment]
After scanning, I entered the settings and could not apply. None of the  transactions, send, etc. can be opened.

**Comment by ibiter** [comment]
So I'm guessing maybe it's being sent via the built-in mint-nft --parent?

**Comment by b456kh** [comment]
![74c720864e76117c0f1326e6c6ec1a8](https://github.com/atomicals/atomicals-js/assets/5693221/b58fb9fc-3755-4be4-9389-da85553fba71)
Right-click on unconfirmed transactions to show up

**Comment by ibiter** [comment]
I know what you're saying, but I can't get to this page. I don't know why this seed phrase doesn't recover the format used🤔

**Comment by ibiter** [comment]
Thanks to b456kh, but he didn't figure out the issue: the original version of Atom used to generate in m/44 format, but now it might have been updated. I tried, and it now generates in m/86.

**Comment by AI-Chef** [comment]
> Thanks to b456kh, but he didn't understand the issue: the original version of Atom used to generate in m/44 format with bc1p, but now it might have been updated. I tried, and it now generates in m/86 with bc1p.

my current question is how to import m/44 format to sparrow wallet?
