### ISSUE TITLE
Invalid Version: 3001.0001.0000-dev-harmony-fb

### ISSUE THREAD

**Issue by aronlee15** [atomicals/atomicals-js#49]
npm ERR! Invalid Version: 3001.0001.0000-dev-harmony-fb

how to fix it？

nodejs and npm are update to the latest version

**Comment by se1k0** [comment]
Normally you can solve this problem by clearing the cache. 
use 
`npm cache clean` or `npm cache clean -f`

If you use yarn, use the command
`yarn cache clean`

**Comment by lucywx** [comment]
i got the same issue.  tried yarn cache clean and it shows the same error.  arghhhh

**Comment by lucywx** [comment]
i switched npm to yarn and it got solved...
