### ISSUE TITLE
Burn my all bitcoin when mint bitwork 

### ISSUE THREAD

**Issue by bberljw** [atomicals/atomicals-js#50]
When executing 'yarn cli mint-dft bitwork,' the console unexpectedly consumes all of my bitcoins for gas, resulting in a gas cost of around 90 USDT.

I suspect there might be a bug in the program.

You can find the details of the transaction [here](https://mempool.space/zh/tx/3726c7e3fc510874748f9ea02d0695d31696d279c238239a19360ab329d4e661).

The commit ID for atomicals-js is 82442ebafbed80177fdd53d4e91be62ee1cf257b. Could you please assist me in resolving these issues?

**Comment by ytjoe** [comment]
Atom version atomicals-js@0.1.46 Cli

I have the same issue, I have set '-- satsbyte 50', but it has cost me all BTC. This is my transaction record, please check
https://mempool.space/zh/address/bc1p4gx62j69zfyzakfwtv3qgt4rpkw0rn7wa6af0dst8knzcmd33ezsaklgrv

**Comment by pan3da** [comment]
A fix has been applied to the `--satsbyte` parameter. Could you please confirm its effectiveness?

**Comment by bberljw** [comment]
Sorry, I am unable to reproduce this bug. And I use --satsbyte  can handle the gas and give a determined gas.
