### ISSUE TITLE
sat is error

### ISSUE THREAD

**Issue by rfk1118** [atomicals/atomicals-js#66]
when i use sat =35 , you can see result  https://mempool.space/address/bc1pdxlnlfgz2nua52ctumhnr2gc2vpv7jwg0vrmflf02a68muewc5usa5vhad 
commit is 400 sat/vB  , rev is 91?   In the past, children were older than their fathers and knew CPFP, but now the gap is too big。

**Comment by Fallenleaf666** [comment]
i have same problem, i use sat =45
https://mempool.space/address/bc1ptlqmpvajt0y8njjl5h02mg0jtu2j2xrfpntyplcvx3rkg4ag3g7sdqslyh
commit around 400 sat/vB

**Comment by williamaronli** [comment]
i meet same issue i set sat =10 why it becomes 320

**Comment by AI-Chef** [comment]
It's not real sat/vB used on blockchain. Don't worry!
